/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as PersonagensIndexRouteImport } from './routes/personagens.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as AnimaisIndexRouteImport } from './routes/animais.index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as PersonagensNovoRouteImport } from './routes/personagens.novo'
import { Route as PersonagensIdRouteImport } from './routes/personagens.$id'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AnimaisNovoRouteImport } from './routes/animais.novo'
import { Route as AnimaisIdRouteImport } from './routes/animais.$id'

const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensIndexRoute = PersonagensIndexRouteImport.update({
  id: '/personagens/',
  path: '/personagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisIndexRoute = AnimaisIndexRouteImport.update({
  id: '/animais/',
  path: '/animais/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensNovoRoute = PersonagensNovoRouteImport.update({
  id: '/personagens/novo',
  path: '/personagens/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensIdRoute = PersonagensIdRouteImport.update({
  id: '/personagens/$id',
  path: '/personagens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisNovoRoute = AnimaisNovoRouteImport.update({
  id: '/animais/novo',
  path: '/animais/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisIdRoute = AnimaisIdRouteImport.update({
  id: '/animais/$id',
  path: '/animais/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/producao': typeof ProducaoRoute
  '/animais/$id': typeof AnimaisIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/personagens/novo': typeof PersonagensNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/animais/': typeof AnimaisIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/personagens/': typeof PersonagensIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/producao': typeof ProducaoRoute
  '/animais/$id': typeof AnimaisIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/personagens/novo': typeof PersonagensNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/animais': typeof AnimaisIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/personagens': typeof PersonagensIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/producao': typeof ProducaoRoute
  '/animais/$id': typeof AnimaisIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/personagens/novo': typeof PersonagensNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/animais/': typeof AnimaisIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/personagens/': typeof PersonagensIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automacao'
    | '/producao'
    | '/animais/$id'
    | '/animais/novo'
    | '/clientes/$id'
    | '/personagens/$id'
    | '/personagens/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/animais/'
    | '/clientes/'
    | '/personagens/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automacao'
    | '/producao'
    | '/animais/$id'
    | '/animais/novo'
    | '/clientes/$id'
    | '/personagens/$id'
    | '/personagens/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/animais'
    | '/clientes'
    | '/personagens'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/automacao'
    | '/producao'
    | '/animais/$id'
    | '/animais/novo'
    | '/clientes/$id'
    | '/personagens/$id'
    | '/personagens/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/animais/'
    | '/clientes/'
    | '/personagens/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomacaoRoute: typeof AutomacaoRoute
  ProducaoRoute: typeof ProducaoRoute
  AnimaisIdRoute: typeof AnimaisIdRoute
  AnimaisNovoRoute: typeof AnimaisNovoRoute
  ClientesIdRoute: typeof ClientesIdRoute
  PersonagensIdRoute: typeof PersonagensIdRoute
  PersonagensNovoRoute: typeof PersonagensNovoRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  AnimaisIndexRoute: typeof AnimaisIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PersonagensIndexRoute: typeof PersonagensIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens/': {
      id: '/personagens/'
      path: '/personagens'
      fullPath: '/personagens/'
      preLoaderRoute: typeof PersonagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/': {
      id: '/animais/'
      path: '/animais'
      fullPath: '/animais/'
      preLoaderRoute: typeof AnimaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens/novo': {
      id: '/personagens/novo'
      path: '/personagens/novo'
      fullPath: '/personagens/novo'
      preLoaderRoute: typeof PersonagensNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens/$id': {
      id: '/personagens/$id'
      path: '/personagens/$id'
      fullPath: '/personagens/$id'
      preLoaderRoute: typeof PersonagensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/novo': {
      id: '/animais/novo'
      path: '/animais/novo'
      fullPath: '/animais/novo'
      preLoaderRoute: typeof AnimaisNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$id': {
      id: '/animais/$id'
      path: '/animais/$id'
      fullPath: '/animais/$id'
      preLoaderRoute: typeof AnimaisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomacaoRoute: AutomacaoRoute,
  ProducaoRoute: ProducaoRoute,
  AnimaisIdRoute: AnimaisIdRoute,
  AnimaisNovoRoute: AnimaisNovoRoute,
  ClientesIdRoute: ClientesIdRoute,
  PersonagensIdRoute: PersonagensIdRoute,
  PersonagensNovoRoute: PersonagensNovoRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  AnimaisIndexRoute: AnimaisIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PersonagensIndexRoute: PersonagensIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
